name: article-matrix-profile-intro
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.17.2=py37haad9e8e_0
  - numpy-base=1.17.2=py37hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_2
  - pcre=8.43=he6710b0_0
  - pip=19.2.3=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - setuptools=41.4.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.30.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h7b6447c_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - attrs==19.2.0
    - backcall==0.1.0
    - bleach==3.1.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ipykernel==5.1.2
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jinja2==2.10.3
    - json5==0.8.5
    - jsonschema==3.0.2
    - jupyter==1.0.0
    - jupyter-client==5.3.3
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - jupyterlab==1.1.4
    - jupyterlab-server==1.0.6
    - markupsafe==1.1.1
    - matrixprofile-ts==0.0.9
    - mistune==0.8.4
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - notebook==6.0.1
    - pandas==0.25.1
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - ptyprocess==0.6.0
    - pygments==2.4.2
    - pyrsistent==0.15.4
    - pyzmq==18.1.0
    - qtconsole==4.5.5
    - send2trash==1.5.0
    - terminado==0.8.2
    - testpath==0.4.2
    - traitlets==4.3.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
